services:
  db:
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=password

  web:
    build: .
    stop_signal: SIGINT
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=UTC
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: flask --app src run --host=0.0.0.0 --port=8000 --debug